runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: ssl
  version: latest
  
# [START handlers]
handlers:
- url: /static
  static_dir: dist
- url: /.*
  script: vue_moment_calendar.app
# [END handlers]
