runtime: python27
api_version: 1
threadsafe: true

# Required for open ssl to work.
libraries:
- name: ssl
  version: latest

# [START handlers]
handlers:
- url: /static
  static_dir: dist
- url: /.*
  script: vue_moment_calendar.app
# [END handlers]

skip_files:
- ^node_modules(/.*)?
- .*node_modules
